/** Curated public guidance. No customer data, persistence or model call. */
export type Qualification = { process: "offers" | "handoff" | "renewals" | "retail"; context: "files" | "crm" | "mixed"; team: "one" | "several" };
const patterns = {
  offers: { risk: "Oferta pleacă, dar revenirea nu primește un termen și un responsabil.", reveal: "Oferta, promisiunea citată și pasul care nu apare în evidențele disponibile.", prepare: "O revenire comercială editabilă, cu întrebarea care trebuie clarificată.", outcome: "Rezultatul ofertei, consemnat separat de estimare, cu autor și motiv." },
  handoff: { risk: "Cazul trece la alt coleg, dar promisiunea rămâne în conversația inițială.", reveal: "Cazul predat, ultima promisiune și responsabilitatea care trebuie confirmată.", prepare: "O propunere de predare cu dovezi, lipsuri și următorul pas de revizuit.", outcome: "Continuarea cazului și rezultatul comercial consemnat de echipă." },
  renewals: { risk: "Relația continuă, însă termenul de reînnoire nu devine o acțiune clară.", reveal: "Contractul, termenul relevant și lipsa unei continuări în sursele disponibile.", prepare: "O propunere de contact pentru clarificarea reînnoirii.", outcome: "Reînnoirea sau închiderea relației, cu valoarea și motivul înregistrate separat." },
  retail: { risk: "O tranzacție instantanee are puține etape de coordonat.", reveal: "Mai întâi verificăm dacă există reveniri, excepții sau relații recurente de urmărit.", prepare: "Delimitarea unui proces cu mai mulți pași, dacă există unul relevant.", outcome: "Un criteriu de utilitate convenit înainte de o eventuală implementare." }
} as const;
export function qualify(input: Qualification) {
  return { ...patterns[input.process], fit: input.process === "retail" ? "Potrivire limitată pentru tranzacții instantanee" : "Un proces potrivit de explorat cu ReveNew", sources: input.context === "files" ? "Conversațiile relevante și registrele CSV/XLSX; documentele selectate pentru caz." : input.context === "crm" ? "Evidențele CRM și sursele ofertei. Accesul și fezabilitatea conectării se evaluează înainte de activare." : "Conversații, întâlniri, documente și evidențele comerciale. Alegem numai sursele necesare procesului.", decision: input.team === "one" ? "Responsabilul comercial, cu dreptul de revizuire stabilit în companie." : "Responsabilul desemnat și persoana autorizată să revizuiască; predarea rămâne explicită." };
}
