import type { CopilotAnswer } from "./copilot-types";
import { findContextualHelp, normalizeHelpText } from "@/lib/contextual-help";

type Guide = { title: string; match: RegExp; route: string; answer: string; steps: string[] };
export const productGuides: Guide[] = [
  { title: "Vizualizări salvate", match: /vizualizar|filtre.*salv/, route: "/companies", answer: "O vizualizare salvată păstrează filtrele și sortarea curentă pentru acces rapid. Este privată, vizibilă numai în contul tău din acest spațiu de lucru.", steps: ["Aplică filtrele și sortarea dorite.", "Deschide Vizualizări salvate, introdu un nume și salvează.", "Apasă numele pentru a o deschide. Folosește creionul pentru redenumire sau coșul pentru ștergere."] },
  { title: "Contact principal", match: /contact.*principal/, route: "/companies", answer: "Contactul principal este persoana de referință a companiei. Îl alegi din contactele asociate, direct în pagina companiei.", steps: ["Deschide compania și apasă Alege contactul principal.", "Selectează persoana sau adaugă un contact nou în aceeași fereastră.", "Confirmă Setează drept contact principal. Responsabilitatea oportunităților rămâne separată."] },
  { title: "Evaluare înainte de implementare", match: /evaluare.*implementare|integrar|aplicatii|sisteme/, route: "/apps", answer: "Evaluare înainte de implementare înseamnă că integrarea nu este disponibilă pentru conectare sau execuție. Procesul, accesul și datele trebuie evaluate înainte de implementare.", steps: ["Disponibil acum: Gmail, Calendar, Drive și fișiere CSV/XLSX, cu accesul și limitele afișate separat.", "Celelalte sisteme prezentate sunt în evaluare. O siglă nu confirmă o conexiune activă."] },
  { title: "Revizuire umană", match: /revizuire umana|aprobar|aprobare|control uman/, route: "/approvals", answer: "O persoană autorizată verifică propunerea, dovezile și efectul înainte de a decide. Pregătit, aprobat și executat sunt stări distincte.", steps: ["Deschide propunerea și verifică sursele și informațiile lipsă.", "Confirmă numai efectul afișat. O aprobare internă nu confirmă trimiterea unui email sau încasarea banilor."] },
  { title: "Workflow-uri", match: /workflow|automatizar|conditie/, route: "/workflows/new", answer: "Descrie regula comercială pentru a pregăti un draft, apoi verifică declanșatorul, condițiile și pașii. Doar primitivele suportate pot fi salvate; activarea se confirmă separat.", steps: ["Semnal → Dovadă / Context → Condiție → Pas pregătit → Revizuire umană.", "Editează definiția și testează pe o oportunitate autorizată. Testul nu execută acțiuni externe.", "Dacă o condiție este falsă, pașii nu se pregătesc. Declanșatorii fără sursă conectată nu pot fi activați."] },
  { title: "Control Center", match: /control center|dashboard/, route: "/dashboard", answer: "Control Center ordonează situațiile pe baza termenelor, responsabilității, pașilor și lucrului în așteptare. Motivul exact al unui caz se verifică în detaliul și dovezile sale.", steps: ["Citește sinteza, apoi selectează cazul din coada de intervenție.", "Verifică De ce acum, responsabilul și următorul pas.", "Aceasta este explicația produsului; fără un caz selectat nu confirmă motivul unui caz anume."] },
  { title: "Inteligență operațională", match: /inteligenta|descoperir|ask|intreaba revenew/, route: "/ai", answer: "Întreabă ReveNew analizează contextul autorizat, iar Descoperiri arată situații identificate din datele disponibile. Ajutorul despre produs este separat de dovezile comerciale.", steps: ["Alege contextul și pune o întrebare concretă.", "Deschide dovezile și verifică limitele. Modelul nu este apelat automat la încărcarea paginii."] },
  { title: "Oportunități și Pipeline", match: /oportunitat|pipeline/, route: "/opportunities", answer: "Oportunitățile leagă compania de un responsabil, o etapă și următorul pas. Pipeline arată poziția lor în proces; valorile rămân estimate până la înregistrarea unui rezultat.", steps: ["Caută sau filtrează registrul și deschide oportunitatea.", "Confirmă responsabilul și pasul cu termen. Modificările sunt verificate la salvare."] },
  { title: "Companii și Company 360", match: /companii|companie|company/, route: "/companies", answer: "Compania reunește oamenii, oportunitățile și contextul comercial asociat. Company 360 prezintă ce necesită atenție și ce urmează.", steps: ["Deschide compania din registru.", "Folosește secțiunile Contacte, Oportunități și Note pentru detalii, sau întreabă în contextul companiei."] },
  { title: "Contacte", match: /contact/, route: "/contacts", answer: "Contactele sunt persoanele implicate în relația comercială. Rolul persoanei și responsabilul intern al unei oportunități sunt informații distincte.", steps: ["Caută persoana după nume sau companie.", "Deschide contactul pentru relații, oportunități și note autorizate."] },
  { title: "Lucru pregătit", match: /lucru pregatit|draft/, route: "/prepared", answer: "Lucru pregătit reunește propunerile și documentele salvate care așteaptă revizuire. Existența unui draft nu înseamnă aprobare sau trimitere.", steps: ["Selectează un element din coadă.", "Verifică motivul, dovezile și efectul exact înainte de următoarea acțiune."] },
  { title: "Documente", match: /document|csv|xlsx|fisier/, route: "/documents", answer: "Documentele păstrează conținutul comercial și sursele locale autorizate. Citirea unui fișier și importarea datelor în CRM sunt acțiuni separate.", steps: ["Deschide documentul sau versiunea sursei.", "Verifică locația citată și acoperirea extracției. Formulele XLSX nu sunt recalculate."] },
  { title: "Întâlniri", match: /intalnir|calendar/, route: "/meetings", answer: "Întâlnirile folosesc contextul Calendar autorizat. Disponibilitatea conectorului nu confirmă conectarea sau existența unei întâlniri.", steps: ["Verifică starea conexiunii în Aplicații.", "Deschide o întâlnire disponibilă și revizuiește contextul înainte de pregătire."] },
  { title: "Secvențe", match: /secvent/, route: "/sequences", answer: "Secvențele organizează pași de comunicare și pregătire. Configurația nu dovedește că un mesaj a fost trimis.", steps: ["Verifică pașii și condițiile de oprire.", "Păstrează revizuirea și confirmarea înainte de execuție externă."] },
  { title: "Activitatea mea", match: /activitatea mea|sarcin/, route: "/today", answer: "Activitatea mea arată acțiunile atribuite ție, ordonate după termen și stare.", steps: ["Începe cu cele restante.", "Deschide cazul și înregistrează progresul real."] },
  { title: "Inbox Comercial", match: /inbox|semnal/, route: "/inbox", answer: "Inbox Comercial este coada de triaj a semnalelor. Un semnal trebuie revizuit înainte de a deveni o schimbare comercială.", steps: ["Selectează semnalul și citește sursa.", "Confirmă identitatea, informațiile lipsă și efectul propus."] },
  { title: "Recuperare comercială", match: /recuperar/, route: "/recoverable", answer: "Recuperarea comercială prioritizează oportunitățile cu lipsuri sau întârzieri. Valoarea expusă este estimată, nu un câștig garantat.", steps: ["Verifică motivul și responsabilul.", "Deschide oportunitatea pentru următorul pas sigur."] },
  { title: "Rapoarte", match: /rapoart|venit|valoare estimata/, route: "/reports", answer: "Rapoartele separă estimările, rezultatele înregistrate și sumele încasate. Monedele și limitele datelor rămân explicite.", steps: ["Alege perioada și verifică definiția indicatorului.", "Deschide datele raportului pentru a verifica valorile."] },
  { title: "Dovezi și filtre", match: /dovez|dovada|filtr|audit|stare|status/, route: "/help", answer: "Dovezile arată sursa și ce susține ea. Filtrele restrâng selecția; stările descriu fapte diferite, iar auditul păstrează schimbările înregistrate.", steps: ["Deschide sursa, versiunea și locația citată când sunt disponibile.", "Verifică informațiile lipsă înainte de a decide."] },
];
export function productHelpAnswer(question: string, route: string, history: ReadonlyArray<{ role: string; content: string }> = []): CopilotAnswer | null {
  const q = normalizeHelpText(question);
  // Resolve only a narrow help follow-up against the previous user question.
  // Assistant text and commercial history never become product documentation.
  if (/^cum (?:se foloseste|se utilizeaza|o folosesc|il folosesc)\??$/.test(q)) {
    const previous = [...history].reverse().find(turn => turn.role === "user");
    return previous ? productHelpAnswer(previous.content, route) : null;
  }
  // Explicit help only: commercial records never become product documentation.
  if (!/^(?:ce face|ce este|ce inseamna|cum (?:se foloseste|se utilizeaza|adaug|aleg|folos|salvez|creez|deschid|modific|sterg|redenume|functioneaza)|unde (?:gasesc|deschid|adaug|salvez)|la ce |explica |de ce apare acest caz in control center)/.test(q)) return null;
  if (/ignora|ocoleste|alte workspace|alte companii|fara permis/.test(q)) return null;
  const guide = productGuides.find(item => item.match.test(q));
  const fallback = guide ? null : findContextualHelp(question, route);
  if (!guide && (!fallback?.matched || !fallback.entry || fallback.score < 30)) return null;
  const answer = guide?.answer ?? fallback!.entry!.shortAnswer;
  const steps = guide?.steps ?? fallback!.entry!.steps;
  return { answer, summaryType: "product_help", productHelp: { title: guide?.title ?? fallback!.entry!.title, steps }, findings: [], evidence: [], checkedSources: [], missingInformation: [], caveats: [], preparedAction: null, suggestedAction: { label: "Deschide " + (guide?.title ?? "Ajutor"), route: guide?.route ?? "/help" }, followUps: [], mode: "deterministic_fallback", providerAvailable: false };
}
